require 'busted.runner'()
FizzBuzz = require("fizz_buzz")

describe("fizz buzz", function()
  describe("Given a 1", function()
    it("returns a 1", function()
      assert.is_equal(1, FizzBuzz.calculate(1))
    end)
  end)

  describe("Given a 2", function()
    it("returns a 2", function()
      assert.is_equal(2, FizzBuzz.calculate(2))
    end)
  end)

  describe("Given a 3", function()
    it("returns Fizz", function()
      assert.is_equal("Fizz", FizzBuzz.calculate(3))
    end)
  end)

  describe("Given a 5", function()
    it("returns Buzz", function()
      assert.is_equal("Buzz", FizzBuzz.calculate(5))
    end)
  end)

  describe("Given a 14", function()
    it("returns 14", function()
      assert.is_equal(14, FizzBuzz.calculate(14))
    end)
  end)

  describe("Given a 15", function()
    it("returns FizzBuzz", function()
      assert.is_equal("FizzBuzz", FizzBuzz.calculate(15))
    end)
  end)
end)